# Generated by Django 4.2.6 on 2023-10-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-created']},
        ),
    ]
